### ISSUE TITLE
fix luasnip's snippet loading

### ISSUE THREAD

**Issue by atauzki** [Shaobin-Jiang/IceNvim#11]
the snippet is not loaded on this configuration. and there are bugs on windows.
see detail: https://github.com/L3MON4D3/LuaSnip/issues/1168
force specifying snippet path works on both windows and linux.

**Comment by Shaobin-Jiang** [comment]
I never realized the plugin is not loaded! Thanks so much for this @atauzki . Fixed this in 218bf9b.
