### ISSUE TITLE
module 'lazy' not found

### ISSUE THREAD

**Issue by Ebbjik** [Shaobin-Jiang/IceNvim#14]
![image](https://github.com/user-attachments/assets/eed3a242-8f27-4fbe-a728-448c777cf1f6)

**Comment by Ebbjik** [comment]
I'm using neovim in a docker image and she uses alpine:latest as the base with jdk17, git and neovim installed。
I just executed git clone https://github.com/Shaobin-Jiang/IceNvim ~/.config/nvim and opened a java file and it showed this

**Comment by Shaobin-Jiang** [comment]
Upon the first launch, IceNvim would try to first download the lazy.nvim plugin manager via `git clone`. Could be a problem with ssl certificate. Maybe you can try `git config --global http.sslVerify false`?

**Comment by Ebbjik** [comment]
我没有太理解（可能我该先尝试简单的）
不过您做的效果确实很好看

**Comment by Ebbjik** [comment]
![image](https://github.com/user-attachments/assets/c1ad9c33-b925-4bc3-a70e-c1359f60348c)
安装上了，不过因为mason之类的问题用不了也是真的（安生vscode吧）
