### ISSUE TITLE
Error during download nvim-treesitter

### ISSUE THREAD

**Issue by 0uroboro5** [Shaobin-Jiang/IceNvim#6]
### Problem

While I was using the IceNVIM configuration, I was waiting to download a tree-sitter and when the progress was at [4/13], the download seemed to be stuck. And an error message pops up after some time: 

```
nvim-treesitter[cpp]: Error during download, please verify your internet connection
Cloning into 'tree-sitter-cpp'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 824 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

This error occurred when I tried to open NEOVIM after clone the IceNVIM repository.

I tried resetting my network or configuring a proxy for WSL2, but nothing worked.

### Neovim version

NVIM v0.10.0-dev-1950+g2877672d7

### Operating system

Ubuntu 22.04 on Windows (WSL2)

### Terminal

Windows Terminal (Preview)

**Comment by Shaobin-Jiang** [comment]
I think that is a problem with your git connection and not with IceNvim. The error clearly occurs during git cloning the parser. You can retry installing it (by re-entering neovim) or you can, as some have suggested, change `http.verion` in your git config: `git config --global http.version HTTP/1.1`.

**Comment by 0uroboro5** [comment]
> I think that is a problem with your git connection and not with IceNvim. The error clearly occurs during git cloning the parser. You can retry installing it (by re-entering neovim) or you can, as some have suggested, change `http.verion` in your git config: `git config --global http.version HTTP/1.1`.

Thanks for your reply, I solved the `curl 92` problem by modifying the `http.version`. The current problem is `RPC failed; curl 18 transfer closed with outstanding read data remaining`. I tried to set this `git config --global http.postBuffer 2097152000` but it doesn't work. I guess it may be a network problem that causes not enough data to be downloaded in a certain period of time. I'm looking for ways to improve my network.
