### ISSUE TITLE
A better way to detect WSL.

### ISSUE THREAD

**Issue by atauzki** [Shaobin-Jiang/IceNvim#9]
I changed my wsl kernel to https://github.com/Locietta/xanmod-kernel-WSL2, but vim's `has("wsl")` doesn't work. so I changed the way to match the kernel version info.
``` lua
utils.is_wsl = function()
    return string.find(vim.loop.os_uname().release, "WSL") ~= nil
end
```

**Comment by Shaobin-Jiang** [comment]
Agreed. The old detection method was a solution I got on vi.stackexchange which was quite old fashioned. This new way of detection is much better. Thanks @atauzki !

Fix for this is made in 4892f81.
